### PR TITLE
Use SYCL 2020 device selectors to quash warnings

### PR DESCRIPTION
**Pull request by JamesEdgeley**
Lines such as `sycl::device default_device{sycl::default_selector()};` in compute_target.hpp have been changed to `sycl::device default_device{sycl::default_selector_v};` to avoid -Wdeprecated-declarations warnings. (oneapi v2024.1)

### CODE REVIEW

**Comment by will-saunders-ukaea** [comment]
Thanks for this - can you check these selectors work with hipsycl 0.9.4 and dpcpp 2022.1.0? I am in favour of moving to the newer selectors but at the back of my mind they were not implemented in the older sycl implementations (which otherwise work fine for us).

**Comment by will-saunders-ukaea** [comment]
Does the [1] `SYCL_LANGUAGE_VERSION` preprocessor definition help distinguish here?

https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#_preprocessor_directives_and_macros

**Comment by JamesEdgeley** [comment]
I think so, hipsycl has 202003 while dpcpp has 202001

**Comment by will-saunders-ukaea** [comment]
Thinking about this some more, I think the way forward is to do something like
```
#ifdef NESO_PARTICLES_LEGACY_DEVICE_SELECTORS
   // existing 1.2 selectors
#else
 // sycl2020 selectors
#endif
```

**Comment by will-saunders-ukaea** [comment]
Thanks - this is looking close. Can you add a cmake option like [1] for `NESO_PARTICLES_LEGACY_DEVICE_SELECTORS` that adds a definition like [2] such that we can do `-DNESO_PARTICLES_LEGACY_DEVICE_SELECTORS=ON` if needed.

[1]  https://github.com/ExCALIBUR-NEPTUNE/NESO-Particles/blob/ba6750d429fe15bbec9b9c507b795cd3117b79b4/CMakeLists.txt#L13
[2] https://github.com/ExCALIBUR-NEPTUNE/NESO-Particles/blob/ba6750d429fe15bbec9b9c507b795cd3117b79b4/CMakeLists.txt#L111

**Comment by will-saunders-ukaea** [comment]
`include/compute_target.hpp` is now in `include/neso_particles/compute_target.hpp` hopefully that is the only merge conflict.

**Comment by JamesEdgeley** [comment]
If the option is not set in the cmake stage do we still want the definition added in preprocessing if using Intel SYCL and version 1.2?

**Comment by will-saunders-ukaea** [comment]
I think how it is now is fine as we know we require it for that case.

**Comment by will-saunders-ukaea** [comment]
My cmake skills are WIP - I am not sure if we should have `add_definitions` and or `target_compile_definitions` maybe @seimtpow can advise.

**Comment by seimtpow** [comment]
I think the "correct way" is to always prefer setting properties on targets rather then setting them globally  so in this case use  target_compile_definitions IMO

**Comment by seimtpow** [comment]
```#if (SYCL_LANGUAGE_VERSION == 202001) && defined(__INTEL_LLVM_COMPILER)```
Is this right should it be < 202001?
FYI my version of icpx reports SYCL_LANGUAGE_VERSION as 202001 and compiles with the new selectors and complains (though still compiles) about the old ones.

**Comment by JamesEdgeley** [comment]
> `#if (SYCL_LANGUAGE_VERSION == 202001) && defined(__INTEL_LLVM_COMPILER)` Is this right should it be < 202001? FYI my version of icpx reports SYCL_LANGUAGE_VERSION as 202001 and compiles with the new selectors and complains (though still compiles) about the old ones.

I was using oneapi/dpcpp 2022.2.1 which also has SYCL_LANGUAGE_VERSION as 202001 but not the new selectors.  Although I understand dpcpp is being deprecated in favour of icpx anyway so it might not be worth catering for it.

**Comment by will-saunders-ukaea** [comment]
I naively assumed that later dpcpp would define a higher sycl language version. This additional conditional solves the warnings for me:
```
#if (SYCL_LANGUAGE_VERSION == 202001) && defined(__INTEL_LLVM_COMPILER)
#if (__INTEL_LLVM_COMPILER < 20230000)
#define NESO_PARTICLES_LEGACY_DEVICE_SELECTORS
#endif
#endif
```

**Comment by will-saunders-ukaea** [comment]
Thanks - let me know if you are happy for me to merge.

**Comment by JamesEdgeley** [comment]
> Thanks - let me know if you are happy for me to merge.

Good to go I think - at some point if we stop supporting dpcpp this can revert to being simpler.

**Pull request merged**
