### PR TITLE
Update particle_io.hpp to work on MacOS

### PR DESCRIPTION
**Pull request by mbukaea**
Fix to allow particle_io.hpp to compile on MacOS

### CODE REVIEW

**Comment by jwscook** [comment]
For some reason it appears that macos has a problem with this combination of use of ifdef and namespace.

**Comment by will-saunders-ukaea** [comment]
There are two changes here: 1) the rearrangement of the ifdefs 2) the change of syntax for nested namespaces. Are both changes needed? I think "namespace A::B{}" is a C++17 feature. 

What is the error from the compiler here? i.e. is the actual problem the compiler using the wrong C++ standard somewhere?

**Comment by mbukaea** [comment]
I have not rearranged any ifdefs. They are still in the same order as they were in the main branch. I have compiled with the c++17 standard it made no difference to the error messages. The error messages were all along the lines of 
/Users/wf5617/NESO/neso-particles/include/particle_io.hpp:21:3: error: no type named 'string' in namespace 'NESO::Particles::std'; did you mean simply 'string'?

For some reason in this one particular file, the nested namespace needs to be defined this way to be able to compile on MacOS, and needed to be split into 2 instead of around the entire if statement. The usual way of defining nested namespaces works in other files.

**Comment by mbukaea** [comment]
I just made some changes to my machine since this morning and now it works in particle_io.hpp using the usual way of writing namespaces, but it still requires it be split into 2 namespaces.

**Comment by mbukaea** [comment]
> > I just made some changes to my machine since this morning and now it works in particle_io.hpp using the usual way of writing namespaces, but it still requires it be split into 2 namespaces.
> 
> Fails with the same error or a new error?
> 
> Does removing the `#include <cstring>` line help? I think I was using memcpy at one point - don't think this is needed now.

It still fails with the same issue. I tried removing #include <cstring> but this didn't fix the issue. As soon as namespace incases the #ifdef NESO_PARTICLES_HDF5 to the end if, it fails

**Comment by will-saunders-ukaea** [comment]
Is it the location of the hdf5 include? That's moving from inside the namespace to outside - probably want it outside the namespace otherwise all the hdf5 definitions will be inside NESO::Particles?

**Comment by mbukaea** [comment]
Moving the include hdf5.h to outside the namespace allowed both neso and neso-particles to build (tests still to be done).

**Comment by jwscook** [comment]
How does that work if NESO-Particles is built without optional HDF5 support?

**Comment by mbukaea** [comment]
The only solution at the moment then is to split the namespace into 2 to avoid include hdf5.h to get a MacOS version, or to put the include hdf5.h line outside the namespace, and encase this line in an #ifdef NESO_PARTICLES_HDF5 ... end if

**Comment by will-saunders-ukaea** [comment]
I suggest wrapping the include in 
```
#ifdef NESO_PARTICLES_HDF5
#include <hdf5.h>
#endif

**Comment by mbukaea** [comment]
I have updated the macOS_fix branch with this solution. @jwscook are you happy with this solution? I will test this on MacOS (Arm), Ubuntu (Arm) and Ubuntu (x86) if everyone is in agreement that this is the best solution.

**Comment by jwscook** [comment]
This is likely the least intrusive solution outside of finding one from the build side of things. Are you happy with this @will-saunders-ukaea ?

**Pull request merged**
